In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import PowerTransformer

********Very important in EDA******
- Missing value analsys is very important in data analysis.
- Its quite natural that dataset has missing values.
- There are so many techniques are there
  - mean
  - median
  - mode
  - bfill (BEfore filling)
  - ffill (Front filling)
  - pad
  - random values
  - you can compare column values and you can impute. 
  - KNN imputer


In [2]:
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1

Names  Ages     City
0  Ramesh  30.0      NaN
1  Suresh  31.0      Hyd
2  Mahesh   NaN     Pune
3     NaN  44.0  Chennai

In [3]:
# Can either give d1.isnull() or d1.isna
d1.isna()
#To know the count in each field of dataframe 
d1.isna().sum()

Names    1
Ages     1
City     1
dtype: int64

In [4]:
dict1={'Names':['Ramesh','Suresh','Mahesh','Null'],
       'Ages':[30,31,'Null',44],
        'City':['Null','Hyd','Pune','Chennai']}
d2 = pd.DataFrame(dict1)
d2.isna()

Names   Ages   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [5]:
dict1={'Names':['Ramesh','Suresh','Mahesh',None],
       'Ages':[30,31,None,44],
        'City':[None,'Hyd','Pune','Chennai']}
d2 = pd.DataFrame(dict1)
d2.isnull()

Names   Ages   City
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

Values are not present,empty box is there ==== Null value
- np.nan 
- None is working
- Some times when you read the csv if you have missing values it shows as Null
- isnull() is the best technique

#Method 1:
Random Filling

Not a good way to fill missing values.

In [6]:
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1.fillna(40,inplace=True)
d1

Names  Ages     City
0  Ramesh  30.0       40
1  Suresh  31.0      Hyd
2  Mahesh  40.0     Pune
3      40  44.0  Chennai

$Method2:$
** Fill the random values based on column 


In [7]:
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1['Ages'].fillna(40,inplace=True) 
d1

Names  Ages     City
0  Ramesh  30.0      NaN
1  Suresh  31.0      Hyd
2  Mahesh  40.0     Pune
3     NaN  44.0  Chennai

$Method3:$ 
    - Mean
    - Median
    - Mode
    
    
- Median does not affect by outliers
- Mean effects by outliers
- If you have data is there 
  - First check the outliers by using simple box plot
  - You can check using outlier function 
  - If you feel outliers are there then fill missing values with median     

In [8]:

#This is for replacing column with  mean 
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)

age_mean=d1['Ages'].mean()
d1['Ages'].fillna(age_mean,inplace=True)
d1


  

Names  Ages     City
0  Ramesh  30.0      NaN
1  Suresh  31.0      Hyd
2  Mahesh  35.0     Pune
3     NaN  44.0  Chennai

In [9]:
#This is for replacing column with  median 
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)

age_median=d1['Ages'].median()
d1['Ages'].fillna(age_median,inplace=True)
d1

Names  Ages     City
0  Ramesh  30.0      NaN
1  Suresh  31.0      Hyd
2  Mahesh  31.0     Pune
3     NaN  44.0  Chennai

**Method4:**
- pad
- bfill
- ffill
- backfill

In [10]:
# In this example if you see , this method pad refers to the previous values of columnto fill 
# For the column axis = 1
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1=d1.fillna(method='pad',axis=1)
d1  

Names    Ages     City
0  Ramesh    30.0     30.0
1  Suresh    31.0      Hyd
2  Mahesh  Mahesh     Pune
3     NaN    44.0  Chennai

In [11]:
#bfill
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1=d1.fillna(method='bfill',axis=0)
d1  

Names  Ages     City
0  Ramesh  30.0      Hyd
1  Suresh  31.0      Hyd
2  Mahesh  44.0     Pune
3     NaN  44.0  Chennai

In [12]:
#ffill
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1=d1.fillna(method='ffill',axis=0)
d1  

Names  Ages     City
0  Ramesh  30.0      NaN
1  Suresh  31.0      Hyd
2  Mahesh  31.0     Pune
3  Mahesh  44.0  Chennai

In [13]:
#backfill
dict1={'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'Ages':[30,31,np.nan,44],
        'City':[np.nan,'Hyd','Pune','Chennai']}
d1 = pd.DataFrame(dict1)
d1=d1.fillna(method='backfill',axis=0)
d1  

Names  Ages     City
0  Ramesh  30.0      Hyd
1  Suresh  31.0      Hyd
2  Mahesh  44.0     Pune
3     NaN  44.0  Chennai

# Categorical Columns
- Categorical columns does not have any meaning mainly in dataframes.
- If it is sometext  or sentence you can find the meaning of the sentence
- For example  Name column is there review column is there 
- Because of only Name itself you can't judge the output
- But a review can impact the output
- Generally if any naive names kind of columns we can fill in any way but if some columns impacting output , then we need 
- to fill those columns with an idean about how that column is related with other columns.

$Method-5$
**KNN imputer**
KNN = k -nearest neighbours
- It is one of ML model to find  the nearest solution based on distance metrics
- Instead of taking all the value of mean
- Why can't we take the neighbours mean of the observation
- Here we choose the neighbours after which the mean calculation of those neighbours  and fill with the mean value.
- KNNImputer takes a two dimension array list not a single dimension array list.
**Package Name**:  sklearn.impute

**Method Name**: KNNImputer

- Test with Numerical Column
- Test with Categorical+Numerical  Column
- 


In [14]:
from sklearn.impute import KNNImputer

In [15]:
#Testing with Numerical Data
two_dimension_arry = np.array([[np.nan,7,4,5],[2,8,4,5],[3,7,4,6],[1,np.nan,np.nan,5]])
print("Before Transformation:",two_dimension_arry)
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
imputed_data=imputer.fit_transform(two_dimension_arry)
print("After Transformation:",imputed_data)


Before Transformation: [[nan  7.  4.  5.]
 [ 2.  8.  4.  5.]
 [ 3.  7.  4.  6.]
 [ 1. nan nan  5.]]
After Transformation: [[1. 7. 4. 5.]
 [2. 8. 4. 5.]
 [3. 7. 4. 6.]
 [1. 7. 4. 5.]]


In [19]:
#Testing with Categorical+ Numerical Column
two_dimension_arry = np.array([[np.nan,7,4,5],[34,8,4,5],[np.nan,7,np.nan,6],[45,np.nan,np.nan,5]])
print("Before Transformation:",two_dimension_arry)
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
imputed_data=imputer.fit_transform(two_dimension_arry)
print("After Transformation:",imputed_data)


Before Transformation: [[nan  7.  4.  5.]
 [34.  8.  4.  5.]
 [nan  7. nan  6.]
 [45. nan nan  5.]]
After Transformation: [[45.  7.  4.  5.]
 [34.  8.  4.  5.]
 [34.  7.  4.  6.]
 [45.  7.  4.  5.]]


In [ ]:
#Testing with Categorical+ Numerical Column
two_dimension_arry = np.array([[np.nan,7,4,5],['Ramesh',8,4,5],['Suresh',7,4,6],['Chandresh',np.nan,np.nan,5]])
print("Before Transformation:",two_dimension_arry)
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
imputed_data=imputer.fit_transform(two_dimension_arry)
print("After Transformation:",imputed_data)
